export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const LOAD_APPLICATION = 'LOAD_APPLICATION';
export const LOAD_APPLICATION_DONE = 'LOAD_APPLICATION_DONE';
export const LOAD_PAGE = 'LOAD_PAGE';
export const LOAD_PAGE_DONE = 'LOAD_PAGE_DONE';
export const UPDATE_SCROLL_STATUS = 'UPDATE_SCROLL_STATUS';
export const FETCH_START = 'FETCH_START';
export const FETCH_DONE = 'FETCH_DONE';
export const CHANGE_PREVENT_LEAVE = 'CHANGE_PREVENT_LEAVE';
export const SET_SITE_FEATURES = 'SET_SITE_FEATURES';
export const FETCH_NETWORK_SUCCESS = 'FETCH_NETWORK_SUCCESS';
export const FETCH_NETWORK_FAIL = 'FETCH_NETWORK_FAIL';

export const CHANGE_HOME_PAGE = 'CHANGE_HOME_PAGE';

// apponiment
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const UPDATE_APPOINTMENT_DONE = 'UPDATE_APPOINTMENT_DONE';
export const UPDATE_APPOINTMENT_FAIL = 'UPDATE_APPOINTMENT_FAIL';
export const FETCH_APPOINTMENT_DONE = 'FETCH_APPOINTMENT_DONE';
export const FETCH_APPOINTMENT_LIST_DONE = 'FETCH_APPOINTMENT_LIST_DONE';
export const SELECT_APPOINTMENT = 'SELECT_APPOINTMENT';

// opportunity
export const UPDATE_OPPORTUNITY = 'UPDATE_OPPORTUNITY';
export const UPDATE_OPPORTUNITY_DONE = 'UPDATE_OPPORTUNITY_DONE';
export const UPDATE_OPPORTUNITY_FAIL = 'UPDATE_OPPORTUNITY_FAIL';
export const FETCH_OPPORTUNITY_DONE = 'FETCH_OPPORTUNITY_DONE';
export const FETCH_OPPORTUNITY_LIST_DONE = 'FETCH_OPPORTUNITY_LIST_DONE';
export const SELECT_OPPORTUNITY = 'SELECT_OPPORTUNITY';
// account

export const FETCH_ACCOUNT_DONE = 'FETCH_ACCOUNT_DONE';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
